version: "3.9"

services:
    api:
        container_name: template
        build:
            context: .
            dockerfile: Dockerfile
            args:
                uid: ${UID}
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 7112:80
        volumes:
            - .:/var/www/html
            - ./vendor:/var/www/html/vendor
        depends_on:
            - mysql
        networks:
            - template
        entrypoint: ["/usr/local/bin/entrypoint.sh"]

    mysql:
        image: mysql:8.0
        container_name: master-database
        ports:
            - 3315:3306
        volumes:
            - ./docker/database/api/run/var:/var/lib/mysql
            - ./docker/database/api/conf/my.cnf:/etc/mysql/my.cnf
            - ./docker/database/api/dump.sql:/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: template
            MYSQL_USER: lucas
            MYSQL_PASSWORD: 123456
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - template

networks:
    template:
        external: true
        name: template
