name: Auto Merge Develop to Master

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Merge develop into master
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin develop
          git merge origin/develop
          git push origin master
